apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: migration-test
  template:
    metadata:
      labels:
        app: migration-test
    spec:
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: migration-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

